devices([
  "iPhone 16 Pro Max",
  "iPhone 16",
  "iPhone SE (3rd generation)",
  "iPad Pro 13-inch (M4)"
])

languages(["en-US"])

scheme("PKMReader")
output_directory("./fastlane/screenshots")

clear_previous_screenshots(true)

erase_simulator(true)

localize_simulator(true)

override_status_bar(true)
