import Foundation

/// A weekly report generated by the AI agent
struct Report: Identifiable, Codable, Sendable {
    /// The S3 key of the report file
    let id: String

    /// The week start date (YYYY-MM-DD)
    let weekOf: String

    /// When the report was last modified
    let modified: Date
}
