import Foundation

/// A weekly report generated by the AI agent
struct Report: Identifiable, Codable, Sendable {
    /// The S3 key of the report file
    let id: String

    /// The week start date (YYYY-MM-DD)
    let weekOf: String

    /// When the report was last modified (optional, not always returned by API)
    let modified: Date?

    init(id: String, weekOf: String, modified: Date? = nil) {
        self.id = id
        self.weekOf = weekOf
        self.modified = modified
    }
}
