import Foundation

/// A weekly report generated by the AI agent
struct Report: Identifiable, Codable, Hashable, Sendable {
    /// The S3 key of the report file
    let id: String

    /// The week start date (YYYY-MM-DD)
    let weekOf: String

    /// When the report was last modified (optional, not always returned by API)
    let modified: Date?

    /// Whether the user has viewed this report (computed server-side from viewed_at vs modified_at)
    let viewed: Bool

    init(id: String, weekOf: String, modified: Date? = nil, viewed: Bool = true) {
        self.id = id
        self.weekOf = weekOf
        self.modified = modified
        self.viewed = viewed
    }

    init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        id = try container.decode(String.self, forKey: .id)
        weekOf = try container.decode(String.self, forKey: .weekOf)
        modified = try container.decodeIfPresent(Date.self, forKey: .modified)
        viewed = try container.decodeIfPresent(Bool.self, forKey: .viewed) ?? true
    }
}
