import Foundation

/// A daily summary generated by the AI agent
struct Summary: Identifiable, Codable, Sendable {
    /// The S3 key of the summary file
    let id: String

    /// The date of the summary (YYYY-MM-DD)
    let date: String

    /// When the summary was last modified
    let modified: Date
}
