import Foundation

/// A daily summary generated by the AI agent
struct Summary: Identifiable, Codable, Hashable, Sendable {
    /// The S3 key of the summary file
    let id: String

    /// The date of the summary (YYYY-MM-DD)
    let date: String

    /// When the summary was last modified (optional, not always returned by API)
    let modified: Date?

    init(id: String, date: String, modified: Date? = nil) {
        self.id = id
        self.date = date
        self.modified = modified
    }
}
